"""Synthetic labelled corpus for text-detector calibration."""
from __future__ import annotations

HUMAN_SAMPLES = [
    "I went to the store. They were out of milk. Got eggs instead.",
    "Walked home in the rain. My shoes are soaked. Worth it though.",
    "Tried that new ramen place last night. Broth was incredible. Noodles a bit soft.",
    "She laughed. He didn't get the joke. Awkward silence for a beat.",
    "My dog ate my homework. Seriously. chewed right through chapter four.",
    "Got the job. Start Monday. Still in shock honestly.",
    "Bus was late again. Walked the last mile. Made it just in time.",
    "Cooked pasta. Burnt the garlic. Started over. Better the second time.",
    "Lost my keys. Found them in the fridge. Don't ask me how.",
    "Saw an old friend today. We hadn't spoken in years. Picked up right where we left off.",
    "Rain. More rain. Then a bit more rain for good measure.",
    "Coffee. Code. More coffee. Debug. Repeat.",
    "He said yes. She said no. The dog said woof. End of meeting.",
    "Skipped lunch. Big mistake. By 3pm I was a hangry monster.",
    "Tried baking bread. It came out like a brick. The birds loved it though.",
    "Missed the train by ten seconds. Watched it pull away. Caught the next one.",
    "Wrote a poem. Threw it out. Wrote another. Kept that one.",
    "My plant died. I watered it too much. Or too little. Hard to say.",
    "Drove three hours for a five minute meeting. Worth it. Closed the deal.",
    "Lost power for six hours. Read a book by candlelight. Honestly kind of nice.",
    "Tried sushi for the first time. The salmon was amazing. The eel not so much.",
    "Got a flat tire on the highway. Changed it in the rain. Made it home.",
    "Found twenty bucks in my old jacket pocket. Best day in weeks.",
    "My grandmother called. We talked for an hour about nothing. Perfect.",
    "Walked to the corner store. Forgot why. Bought gum. Walked back.",
    "Cat knocked over my coffee. All over the keyboard. Fun morning.",
    "Tried to fix the leaky faucet. Made it worse. Called a plumber.",
    "Finished the book. Cried at the end. Started the next one immediately.",
    "Got stuck in traffic. Missed the movie. Caught dinner instead. Better night.",
    "My kid said the funniest thing today. I laughed so hard I cried.",
    "Ran five miles. Walked the last two. Still counts.",
    "Burnt the toast. Scraped off the black. Ate it anyway. With extra jam.",
    "Tried the new coffee shop. Slow service. Great latte though.",
    "Lost my phone in the couch cushions. Found it three days later. Battery dead.",
    "Planted tomatoes. The squirrels got them all. Every single one.",
    "Watched the sunset from the roof. Took zero photos. Just watched.",
    "Got a haircut. Too short. It'll grow back. Eventually.",
    "Made soup from scratch. Took four hours. Worth every minute.",
    "My neighbor's dog escaped. We chased it for an hour. Caught it. Good boy.",
    "Tried knitting. Made a scarf. It's three feet too long. Still wearable.",
]

AI_SAMPLES = [
    "It is important to note that this system represents a comprehensive approach to addressing the multifaceted challenges inherent in modern content verification. Furthermore, the implementation of said framework necessitates a thorough understanding of the underlying methodologies.",
    "In conclusion, the aforementioned analysis demonstrates that the proposed methodology offers significant advantages over traditional approaches. Moreover, the results indicate a substantial improvement in overall accuracy and reliability across various use cases.",
    "The implementation of this framework requires careful consideration of multiple factors. Additionally, it is essential to ensure that all stakeholders are properly consulted throughout the process. Furthermore, ongoing monitoring and evaluation are critical to long-term success.",
    "This comprehensive guide provides a detailed overview of the subject matter. In addition, it offers practical recommendations for implementation. Furthermore, the document includes relevant case studies and best practices to facilitate understanding.",
    "It is worth noting that the current approach has several limitations that should be addressed in future iterations. Nevertheless, the foundational principles remain sound and provide a solid basis for continued development and refinement.",
    "The following section outlines the key components of the proposed solution. First, it is important to understand the underlying architecture. Additionally, the integration points must be clearly defined. Finally, the deployment strategy should be carefully planned.",
    "In today's rapidly evolving technological landscape, it has become increasingly important to adopt a strategic approach to digital transformation. Furthermore, organizations must remain agile and responsive to changing market conditions. Additionally, the role of leadership cannot be overstated.",
    "This analysis demonstrates that the proposed solution offers a robust and scalable approach to the problem at hand. Moreover, the implementation strategy outlined herein provides a clear roadmap for successful deployment. In addition, the framework accommodates future growth and adaptation.",
    "The research findings indicate that there are several factors contributing to this phenomenon. First and foremost, it is essential to consider the contextual variables. Furthermore, the methodology employed must be rigorously validated. Finally, the implications of these findings warrant further investigation.",
    "It is crucial to recognize that effective communication plays a vital role in organizational success. Moreover, the establishment of clear protocols and procedures ensures consistency across all levels of operation. Additionally, regular training and development opportunities contribute to long-term effectiveness.",
    "The following recommendations are provided to guide implementation efforts. Firstly, a comprehensive assessment of current capabilities should be conducted. Secondly, a detailed action plan must be developed. Thirdly, appropriate resources should be allocated. Finally, ongoing evaluation mechanisms should be established.",
    "In summary, the integration of these methodologies represents a significant advancement in the field. Furthermore, the practical applications are numerous and varied. Additionally, continued research in this area will undoubtedly yield further insights and improvements.",
    "This document serves as a foundational reference for the initiative. It is important to note that successful implementation requires commitment from all stakeholders. Moreover, regular progress reviews should be conducted. Furthermore, flexibility in execution is recommended to accommodate unforeseen challenges.",
    "The proposed approach leverages established best practices while incorporating innovative elements. Additionally, it addresses the limitations identified in previous iterations. Furthermore, the framework is designed to be both modular and extensible, facilitating future enhancements and modifications.",
    "It is essential to understand that the success of any initiative depends largely on effective planning and execution. Moreover, the allocation of appropriate resources cannot be overlooked. Additionally, the establishment of clear metrics for success is paramount to ensuring accountability and transparency.",
    "The analysis presented herein offers a comprehensive examination of the subject. Furthermore, it provides actionable insights that can be readily applied. In addition, the recommendations are grounded in empirical evidence and supported by extensive research.",
    "This framework has been designed with scalability in mind. It is worth noting that the modular architecture facilitates seamless integration with existing systems. Moreover, the documentation provided ensures that implementation teams have the necessary guidance. Additionally, ongoing support is available.",
    "In considering the various options available, it becomes evident that the proposed solution offers the most balanced approach. Furthermore, the cost-benefit analysis strongly supports this conclusion. Additionally, the implementation timeline is realistic and achievable.",
    "The key takeaway from this analysis is that a holistic approach yields the best results. Moreover, the interplay between various components must be carefully managed. Furthermore, regular calibration and adjustment are necessary to maintain optimal performance.",
    "It is important to emphasize that this is not a one-time effort but rather an ongoing process. Furthermore, the framework should be reviewed and updated periodically. Additionally, feedback from stakeholders should be actively solicited and incorporated.",
    "The following considerations should guide decision-making. First, the strategic alignment with organizational objectives must be verified. Second, the technical feasibility should be assessed. Third, the financial implications require careful analysis. Finally, the risk factors must be thoroughly evaluated.",
    "This comprehensive approach ensures that all aspects of the problem are addressed. Moreover, the methodology is both systematic and repeatable. Furthermore, the documentation provided serves as a valuable reference for future initiatives of a similar nature.",
    "In light of the foregoing analysis, it is recommended that the proposed course of action be adopted. Furthermore, the implementation should proceed in a phased manner to minimize disruption. Additionally, a dedicated project team should be established to oversee execution.",
    "The benefits of this approach are multifaceted. Firstly, it improves operational efficiency. Secondly, it enhances overall quality. Thirdly, it reduces long-term costs. Moreover, it positions the organization for future growth. Additionally, it fosters a culture of continuous improvement.",
    "It should be noted that the successful adoption of this framework requires a cultural shift within the organization. Furthermore, leadership must actively champion the initiative. Moreover, adequate training and support must be provided. Additionally, early wins should be celebrated to build momentum.",
    "The following section provides a detailed examination of the various components. It is important to note that each component plays a critical role in the overall system. Furthermore, the interactions between components must be carefully orchestrated. Additionally, the failure modes should be understood.",
    "This analysis has revealed several important insights. Firstly, the current approach is suboptimal. Secondly, significant opportunities for improvement exist. Thirdly, the proposed solution addresses these gaps effectively. Moreover, the implementation strategy is sound. Furthermore, the expected outcomes are well-defined.",
    "In conclusion, the proposed framework represents a significant step forward. Moreover, it addresses the key challenges identified in the analysis. Furthermore, the implementation plan is both comprehensive and practical. Additionally, the expected benefits justify the investment required.",
    "The following recommendations should be implemented in sequence. First, the foundational elements must be established. Second, the core functionality should be deployed. Third, the advanced features can be rolled out. Furthermore, each phase should be thoroughly tested. Finally, ongoing maintenance is essential.",
    "It is worth emphasizing that this framework is not prescriptive but rather adaptable to specific organizational contexts. Moreover, the principles can be tailored to fit various scenarios. Furthermore, the flexibility of the approach is one of its key strengths. Additionally, regular reviews ensure continued relevance.",
    "The integration of these methodologies requires careful planning. Furthermore, the technical infrastructure must be adequately provisioned. Moreover, the team should possess the requisite skills. Additionally, external expertise may be required in certain areas.",
    "This document has presented a comprehensive analysis of the subject matter. Furthermore, it has offered practical recommendations grounded in current best practices. Moreover, the framework provided is both robust and flexible. Additionally, it accommodates the unique needs of various stakeholders.",
    "In considering the way forward, several factors must be taken into account. First, the current state of affairs must be honestly assessed. Second, the desired end state should be clearly defined. Third, the gap between the two must be analyzed. Furthermore, a realistic plan must be developed. Finally, execution must be disciplined.",
    "The success of this initiative depends on several key factors. Moreover, these factors are interrelated and must be addressed holistically. Furthermore, the sequencing of activities is critical. Additionally, the allocation of resources must be carefully managed.",
    "It is important to recognize that this is a complex undertaking. Furthermore, the path forward will not always be straightforward. Moreover, adjustments will be necessary along the way. Additionally, the ability to adapt to changing circumstances will be a key determinant of success.",
    "The following guidelines should be adhered to throughout the implementation. First, communication must be clear and consistent. Second, decisions should be evidence-based. Third, risks must be proactively managed. Furthermore, progress should be regularly reviewed. Finally, lessons learned should be documented.",
    "This framework has been developed through extensive research and consultation. Furthermore, it incorporates lessons learned from previous initiatives. Moreover, it reflects current best practices in the field. Additionally, it has been validated through pilot testing.",
    "In summary, the adoption of this framework will yield significant benefits. Moreover, the risks of non-adoption are substantial. Furthermore, the cost of implementation is justified by the expected returns. Additionally, the timing is opportune given current market conditions.",
    "The following action items should be prioritized. First, the governance structure should be established. Second, the technical architecture should be finalized. Third, the implementation plan should be developed. Furthermore, the budget should be secured. Finally, the team should be assembled.",
    "It is essential to maintain a long-term perspective throughout this initiative. Furthermore, short-term challenges should not derail the overall strategy. Moreover, regular reassessment is necessary to ensure continued alignment with organizational objectives. Additionally, flexibility and adaptability are key.",
]


def load_corpus() -> list[tuple[str, int]]:
    """Return a list of (text, label) tuples. label=1 means AI-generated."""
    return [(t, 0) for t in HUMAN_SAMPLES] + [(t, 1) for t in AI_SAMPLES]
